---

common_packages:
  - exuberant-ctags
  - gcc
  - git
  - htop
  - make
  - mosh
  - nload
  - nmap
  - silversearcher-ag
  - tmux
  - tree
  - vnstat
  - xsel

common_fasd_release_hash: '4822024'
common_fasd_url: 'https://github.com/clvv/fasd/tarball/1.0.1'
common_fasd_dir: 'clvv-fasd-{{ common_fasd_release_hash }}'
