---

- name: Install Python
  apt: name={{ item }}
  with_items:
    - python
    - python-dev
    - python3
    - python3-dev

- name: Install Pip
  apt: name={{ item }}
  with_items:
    - python-pip
    - python3-pip

- name: Install global packages for Python 2
  pip: name={{ item }} executable=pip2
  with_items: python_2_global_packages

- name: Install global packages for Python 3
  pip: name={{ item }} executable=pip3
  with_items: python_3_global_packages

- name: Set virtualenv directory
  lineinfile: >
    dest='{{ python_shell_rc_file }}'
    regexp='^export WORKON_HOME='
    line='export WORKON_HOME={{ python_virtualenv_dir }}'
    state=present

- name: Source virtualenvwrapper script
  lineinfile: >
    dest='{{ python_shell_rc_file }}'
    line='source /usr/local/bin/virtualenvwrapper.sh'
    state=present
